### PR TITLE
WP-1099 visual tests for Checkbox

### PR DESCRIPTION
**Pull request by sergeychernyshev**
Visual tests for Checkbox.

JIRA: https://meetup.atlassian.net/browse/WP-1099

### CODE REVIEW

**Comment by jaclynj** [comment]
The snapshots don't have the icon inside the checkbox.

**Comment by sadafie** [comment]
Anytime you rename a test suite, it'll rename the snapshot so you'll have to manually delete this unused snapshot file - `src/__image_snapshots__/checkbox-test-jsx-checkbox-default-1-snap.png`. Also this is updating button and other snapshots, why? is this the font thing again?

**Comment by sergeychernyshev** [comment]
Yeah, snapshots got updated because of platform discrepancy issues - reverted them to what's on master.

As for extra snapshot file `checkbox-test-jsx-checkbox-default-1-snap.png`, it's actually not there, it is listed, but as deleted file.

**Comment by sergeychernyshev** [comment]
@sadafie, can you take a (hopefully final) look at it? Hope it's in a good enough shape now.

**Comment by sadafie** [comment]
@sergeychernyshev if you pull the latest master, you can convert these to jest snapshots. it's very simple, you can use Button.test.jsx as an example.

**Comment by sergeychernyshev** [comment]
Replaced with https://github.com/meetup/swarm-ui/pull/86

**Pull request closed without merging**
